apiVersion: v1
kind: Service
metadata:
  name: welcome-svc
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: welcome-app
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: welcome-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: welcome-app
  template:
    metadata:
      labels:
        app: welcome-app
    spec:
      containers:
      - image: 192.168.0.33/devops/cicd-web-project:2
        imagePullPolicy: IfNotPresent
        name: cicd-web-project
        ports:
        - containerPort: 8080
          protocol: TCP
      imagePullSecrets:
      - name: regcred
