version: "3.1"
services:
  my-db:
    platform: linux/amd64 # for apple chip
    image: mariadb:latest
    environment: 
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=true
      - MARIADB_DATABASE=mydb
    ports:
      - 3306:3306
    volumes: 
      - ${my-home}/devops-docker/docker-compose/data:/var/lib/mysql # for macos
    networks:
      - my-network

  my-backend:
    image: ${my-repo}/my-backend:1.0
    environment: 
      - spring.datasource.url=jdbc:mariadb://my-db:3306/mydb
      - spring.datasource.password=
    ports:
      - 8088:8088
    depends_on:
      - my-db
    networks:
      - my-network

  my-frontend:
    image: ${my-repo}/my-frontend:1.0
    ports:
      - 80:80
    depends_on:
      - my-db
    networks:
      - my-network

networks:
  my-network:
    external: true
      
